#!/usr/bin/env python3
# Sadot — terrain TIN + contour-line generator, authored 2026-07-08 (team_110, tooling-architecture WP).
#
# WHY THIS EXISTS: real construction-grade grading needs a terrain surface driven by actual survey spot
# elevations, not free-hand Blender sculpting. This script takes a point cloud (easting, northing, elevation —
# ITM/EPSG:2039 meters) and produces:
#   1. A Delaunay-triangulated surface mesh (OBJ) — importable into Blender as the base terrain.
#   2. Contour polylines at a configurable interval (default 0.25m) — for construction-document overlays and
#      for verifying grading changes against real elevation data during S002/S003 design.
#
# DATA STATUS (2026-07-08): only 6 real boundary-vertex coordinates (easting/northing) are digitized so far
# (blender/data/site/SITE_GEO.yaml `boundary_itm`), and only 2 individual spot elevations have a confidently
# known (E,N) location (~57.59m near the NW corner by parcel 121, ~54.47m near boundary point 3G — see
# design/CANONICAL/02_SPATIAL_SSOT_and_GEOMETRY.md). The source PDF has NO embedded text layer (it's a
# scanned/CAD-exported raster) — accurately reading all ~40 spot-elevation labels AND their precise pixel
# positions by eye is exactly the kind of manual-transcription task that produced the fabricated tree-count
# error caught in this project's completion audit. DO NOT hand-digitize the remaining ~38 points from the
# raster scan as a shortcut.
#
# RECOMMENDED PATH TO REAL DATA: ask מודדי עירון (the surveyor, contact in the PDF title block) or Niv Sadot
# for the DIGITAL point list / DWG / DXF the survey was originally produced from. A real point-list (typically
# a .csv/.txt of point-id,easting,northing,elevation, or a DWG with POINT/TEXT entities) gives exact values —
# incomparably more reliable than visual raster reading, and is standard practice to request for this kind of
# work. Once that file exists, feed it to `load_points_from_csv()` below instead of the DEMO_POINTS placeholder.

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

import numpy as np
from scipy.spatial import Delaunay

# The 6 real, survey-confirmed boundary points (blender/data/site/SITE_GEO.yaml `boundary_itm`).
# Elevation values here are DEMO placeholders except 3G (54.47, confidently located near this corner) —
# do NOT treat the other 5 as real; they exist only so this script has enough points to triangulate for
# testing. Replace this whole list once a real point file exists (see load_points_from_csv).
DEMO_POINTS = [
    # (point_id, easting_m, northing_m, elevation_m, is_real_elevation)
    ("1G", 196695.299, 707864.034, 56.5, False),
    ("2G", 196701.014, 707864.620, 56.6, False),
    ("3G", 196694.530, 707812.220, 54.47, True),   # real — confirmed near this corner
    ("4G", 196684.489, 707813.303, 54.9, False),
    ("5G", 196680.410, 707860.480, 57.2, False),
    ("6G", 196695.580, 707862.030, 57.4, False),
]


def load_points_from_csv(path: str) -> list[tuple[str, float, float, float, bool]]:
    """Load a real point list: columns point_id,easting_m,northing_m,elevation_m (header row required)."""
    pts = []
    with open(path, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            pts.append((row["point_id"], float(row["easting_m"]), float(row["northing_m"]), float(row["elevation_m"]), True))
    return pts


def triangulate(points: list[tuple[str, float, float, float, bool]]):
    """Delaunay triangulation in the horizontal (E,N) plane; Z carried along per-vertex."""
    xy = np.array([(p[1], p[2]) for p in points])
    z = np.array([p[3] for p in points])
    tri = Delaunay(xy)
    return xy, z, tri


def write_obj(path: str, xy: np.ndarray, z: np.ndarray, tri: Delaunay, origin: tuple[float, float] | None = None):
    """Write a Blender-importable OBJ. Coordinates are re-based to `origin` (default: first point) so the
    mesh sits near the world origin in Blender rather than at raw ITM easting/northing magnitudes (~10^5-10^6),
    which exceeds Blender's comfortable single-precision working range."""
    if origin is None:
        origin = (xy[0, 0], xy[0, 1])
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Sadot terrain TIN — generated by generate_terrain_tin.py\n")
        f.write(f"# origin (subtracted from all coords): easting={origin[0]:.3f} northing={origin[1]:.3f}\n")
        for i in range(len(xy)):
            x = xy[i, 0] - origin[0]
            y = xy[i, 1] - origin[1]
            f.write(f"v {x:.4f} {y:.4f} {z[i]:.4f}\n")
        for simplex in tri.simplices:
            a, b, c = (simplex + 1)  # OBJ is 1-indexed
            f.write(f"f {a} {b} {c}\n")


def generate_contours(xy: np.ndarray, z: np.ndarray, tri: Delaunay, interval: float = 0.25):
    """Marching-triangles contour extraction. Returns {elevation: [ (x1,y1)-(x2,y2) segment, ... ]}."""
    z_min, z_max = float(z.min()), float(z.max())
    levels = np.arange(np.floor(z_min / interval) * interval, np.ceil(z_max / interval) * interval + interval, interval)
    contours: dict[float, list] = {}
    for level in levels:
        segments = []
        for simplex in tri.simplices:
            verts = [(xy[i, 0], xy[i, 1], z[i]) for i in simplex]
            crossings = []
            for (x1, y1, z1), (x2, y2, z2) in [(verts[0], verts[1]), (verts[1], verts[2]), (verts[2], verts[0])]:
                if (z1 - level) * (z2 - level) < 0:
                    t = (level - z1) / (z2 - z1)
                    crossings.append((x1 + t * (x2 - x1), y1 + t * (y2 - y1)))
            if len(crossings) == 2:
                segments.append((crossings[0], crossings[1]))
        if segments:
            contours[round(float(level), 3)] = segments
    return contours


def write_contours_geojson_like(path: str, contours: dict, origin: tuple[float, float]):
    """Write contour segments as a simple JSON structure (not true GeoJSON — local ITM-relative coords)."""
    out = {"origin_easting": origin[0], "origin_northing": origin[1], "unit": "meters", "levels": []}
    for level, segments in sorted(contours.items()):
        out["levels"].append({
            "elevation_m": level,
            "segments": [[[p1[0] - origin[0], p1[1] - origin[1]], [p2[0] - origin[0], p2[1] - origin[1]]] for p1, p2 in segments],
        })
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--points-csv", help="Real point-list CSV (point_id,easting_m,northing_m,elevation_m). "
                                          "Omit to run on DEMO_POINTS (boundary-only, mostly placeholder elevations).")
    ap.add_argument("--interval", type=float, default=0.25, help="Contour interval in meters (default 0.25)")
    ap.add_argument("--out-dir", default=".", help="Output directory for terrain.obj / contours.json")
    args = ap.parse_args()

    points = load_points_from_csv(args.points_csv) if args.points_csv else DEMO_POINTS
    if not args.points_csv:
        print("WARNING: running on DEMO_POINTS — boundary geometry is real, but only 1 of 6 elevations "
              "(3G, 54.47m) is survey-confirmed. This proves the pipeline works; it is NOT a real terrain "
              "model. Request the surveyor's digital point file before using this for actual design work.",
              file=sys.stderr)

    xy, z, tri = triangulate(points)
    origin = (xy[0, 0], xy[0, 1])

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    obj_path = out_dir / "terrain.obj"
    contours_path = out_dir / "contours.json"

    write_obj(str(obj_path), xy, z, tri, origin=origin)
    contours = generate_contours(xy, z, tri, interval=args.interval)
    write_contours_geojson_like(str(contours_path), contours, origin)

    print(f"Wrote {obj_path} ({len(tri.simplices)} triangles) and {contours_path} ({len(contours)} contour levels)")


if __name__ == "__main__":
    main()
